version: "2.1"

services:
  node:
    container_name: projetohqfrontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200